// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID           int64
	Name         string
	TargetAmount *int64
	UserID       int64
}

type Expense struct {
	ID         int64
	Name       string
	Amount     int64
	CategoryID *int64
	UserID     int64
}

type Goal struct {
	ID           int64
	Name         string
	TargetAmount *int64
	UserID       int64
}

type Income struct {
	ID           int64
	Name         string
	Amount       int64
	TargetSaving int64
	ReceivedAt   pgtype.Timestamptz
	UserID       int64
}

type Saving struct {
	ID     int64
	Name   string
	Amount int64
	GoalID *int64
	UserID int64
}

type User struct {
	ID        int64
	Email     string
	Password  string
	FirstName string
	LastName  *string
	CreatedAt pgtype.Timestamptz
}
